# Generated by Django 4.1.2 on 2022-12-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0015_cart_colour_cart_size_purchase_colour_purchase_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='User3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Логин')),
                ('password', models.TextField(max_length=255, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
