# Generated by Django 4.1.2 on 2022-12-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0016_user3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user3d',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль'),
        ),
    ]
