# Generated by Django 4.1.2 on 2022-12-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0018_alter_user3d_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user3d',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
    ]
