# Generated by Django 4.1.2 on 2022-12-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0020_sell3d_compl_date_sell3d_del_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell3d',
            name='change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='sell3d',
            name='compl_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='sell3d',
            name='del_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата удаления'),
        ),
    ]
