# Generated by Django 4.1.1 on 2022-12-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0021_sell3d_change_date_alter_sell3d_compl_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='image_path',
            field=models.ImageField(default='images/1.png', upload_to='images', verbose_name='Фото модели'),
        ),
    ]
