# Generated by Django 4.1.1 on 2022-12-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0009_remove_sell3d_colour_remove_sell3d_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell3d',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
