# Generated by Django 4.1.2 on 2022-11-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0004_alter_model3d_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='image_path',
            field=models.ImageField(upload_to='images', verbose_name='Фото модели'),
        ),
    ]
