# Generated by Django 4.1.1 on 2022-12-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0010_alter_sell3d_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell3d',
            name='id_purchase',
            field=models.IntegerField(default=0, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
