# Generated by Django 4.1.2 on 2022-12-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0013_remove_sell3d_id_purchase_purchase_id_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User3d',
        ),
        migrations.AddField(
            model_name='sell3d',
            name='comment',
            field=models.TextField(default='', max_length=8000, verbose_name='Комментарий'),
        ),
    ]
