# Generated by Django 4.1.2 on 2022-12-25 18:40

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0017_alter_user3d_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user3d',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user3d',
            old_name='is_admin',
            new_name='is_superuser',
        ),
        migrations.AddField(
            model_name='user3d',
            name='email',
            field=models.CharField(default='', max_length=20, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='user3d',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
