# Generated by Django 4.1.1 on 2022-09-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printwebsite', '0002_book_remove_model_3d_list_3d_delete_list_3d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'Models',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
