# Generated by Django 4.1.1 on 2022-09-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printwebsite', '0003_model3d_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
