# Generated by Django 4.1.1 on 2022-12-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0011_sell3d_id_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell3d',
            name='id_model',
        ),
        migrations.RemoveField(
            model_name='sell3d',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('id_model', models.ForeignKey(db_column='model', on_delete=django.db.models.deletion.DO_NOTHING, to='printing3d.model3d', verbose_name='Модель')),
            ],
        ),
    ]
