# Generated by Django 4.1.2 on 2022-12-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0014_delete_user3d_sell3d_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='colour',
            field=models.CharField(default='серый', max_length=255, verbose_name='Цвет модели'),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.IntegerField(default=28, verbose_name='Размер модели'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='colour',
            field=models.CharField(default='серый', max_length=255, verbose_name='Цвет модели'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='size',
            field=models.IntegerField(default=28, verbose_name='Размер модели'),
        ),
    ]
