# Generated by Django 4.1.2 on 2022-11-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0005_alter_model3d_image_path_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='количество'),
            preserve_default=False,
        ),
    ]
