# Generated by Django 4.1.1 on 2022-09-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='model_3d',
            name='list_3d',
        ),
        migrations.DeleteModel(
            name='List_3D',
        ),
        migrations.DeleteModel(
            name='Model_3D',
        ),
    ]
