# Generated by Django 4.1.2 on 2022-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0002_model3d_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='image_path',
            field=models.CharField(max_length=50, null=True, verbose_name='Фото модели'),
        ),
        migrations.AlterField(
            model_name='sell3d',
            name='size',
            field=models.IntegerField(verbose_name='Размер модели'),
        ),
    ]
