# Generated by Django 4.1.1 on 2022-12-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printing3d', '0008_alter_cart_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell3d',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='sell3d',
            name='size',
        ),
        migrations.AddField(
            model_name='sell3d',
            name='quantity',
            field=models.ForeignKey(db_column='quantity', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='printing3d.cart', verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell3d',
            name='status',
            field=models.IntegerField(default=1, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='sell3d',
            name='id_user',
            field=models.IntegerField(verbose_name='Пользователь'),
        ),
    ]
