# Generated by Django 4.1.2 on 2022-10-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('description', models.TextField(max_length=8000, verbose_name='Описание модели')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена модели')),
            ],
        ),
        migrations.CreateModel(
            name='User3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(max_length=255, verbose_name='Логин')),
                ('password', models.TextField(max_length=255, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Sell3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateTimeField(auto_now=True, verbose_name='Дата продажи')),
                ('colour', models.CharField(max_length=255, verbose_name='Цвет модели')),
                ('size', models.IntegerField(max_length=255, verbose_name='Размер модели')),
                ('id_model', models.ForeignKey(db_column='model', on_delete=django.db.models.deletion.DO_NOTHING, to='printing3d.model3d', verbose_name='Модель')),
                ('id_user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='printing3d.user3d', verbose_name='Пользователь')),
            ],
        ),
    ]
